const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "+234 907 853 2947";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_12_23_09_01_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDAsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTc4LFxuICAgICAgICA5OCxcbiAgICAgICAgMjAzLFxuICAgICAgICA0NyxcbiAgICAgICAgNTEsXG4gICAgICAgIDIxMCxcbiAgICAgICAgNjUsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTM5LFxuICAgICAgICAwLFxuICAgICAgICAzOCxcbiAgICAgICAgMTYyLFxuICAgICAgICAxODIsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTMyLFxuICAgICAgICAyMTMsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTE3LFxuICAgICAgICA4MSxcbiAgICAgICAgMTE1LFxuICAgICAgICAyNDAsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTIyLFxuICAgICAgICA5OCxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxMjgsXG4gICAgICAgIDE1LFxuICAgICAgICAxODYsXG4gICAgICAgIDE2NyxcbiAgICAgICAgODdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDUsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTgsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMjIzLFxuICAgICAgICA4NyxcbiAgICAgICAgNTEsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNTEsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMyxcbiAgICAgICAgMTkzLFxuICAgICAgICAxNjIsXG4gICAgICAgIDczLFxuICAgICAgICAzNCxcbiAgICAgICAgODIsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTc2LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTIxLFxuICAgICAgICAxMDQsXG4gICAgICAgIDEsXG4gICAgICAgIDM1LFxuICAgICAgICAyMzgsXG4gICAgICAgIDE1MCxcbiAgICAgICAgNixcbiAgICAgICAgNzAsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTU2LFxuICAgICAgICAyMzAsXG4gICAgICAgIDkwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDQsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTU2LFxuICAgICAgICAxNTEsXG4gICAgICAgIDUwLFxuICAgICAgICAxOTEsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTk3LFxuICAgICAgICAxNDgsXG4gICAgICAgIDIxMixcbiAgICAgICAgMjEzLFxuICAgICAgICAyMDQsXG4gICAgICAgIDE4LFxuICAgICAgICAxMzcsXG4gICAgICAgIDQ0LFxuICAgICAgICA5MCxcbiAgICAgICAgMTI1LFxuICAgICAgICAxMzgsXG4gICAgICAgIDUxLFxuICAgICAgICA3MixcbiAgICAgICAgMTQyLFxuICAgICAgICAxNTYsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTg4LFxuICAgICAgICAyMzgsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTk0LFxuICAgICAgICAxODUsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjAxLFxuICAgICAgICAxNDksXG4gICAgICAgIDgzXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDY3LFxuICAgICAgICAxMjksXG4gICAgICAgIDEzMixcbiAgICAgICAgMjE4LFxuICAgICAgICAyMixcbiAgICAgICAgODIsXG4gICAgICAgIDY1LFxuICAgICAgICAyMzQsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjQ2LFxuICAgICAgICA3NixcbiAgICAgICAgODEsXG4gICAgICAgIDYzLFxuICAgICAgICAxNDcsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTk3LFxuICAgICAgICA0MixcbiAgICAgICAgMTAzLFxuICAgICAgICAzMCxcbiAgICAgICAgMTksXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTE1LFxuICAgICAgICAyNixcbiAgICAgICAgNTksXG4gICAgICAgIDQ3LFxuICAgICAgICAyMTIsXG4gICAgICAgIDExOCxcbiAgICAgICAgMjU1LFxuICAgICAgICAxNSxcbiAgICAgICAgNjcsXG4gICAgICAgIDIzNixcbiAgICAgICAgNTFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyMCxcbiAgICAgICAgODMsXG4gICAgICAgIDE5LFxuICAgICAgICAyMjgsXG4gICAgICAgIDEyNCxcbiAgICAgICAgOCxcbiAgICAgICAgOTUsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTIzLFxuICAgICAgICA1OCxcbiAgICAgICAgMTkwLFxuICAgICAgICAxMTUsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjQ3LFxuICAgICAgICAxODQsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjAwLFxuICAgICAgICAxODYsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTI4LFxuICAgICAgICAyOCxcbiAgICAgICAgMTk2LFxuICAgICAgICA3NixcbiAgICAgICAgODAsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTgyLFxuICAgICAgICA0NCxcbiAgICAgICAgOSxcbiAgICAgICAgMTUsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjMxLFxuICAgICAgICA2NVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNzcsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMzgsXG4gICAgICAgIDMyLFxuICAgICAgICA2NyxcbiAgICAgICAgMTk5LFxuICAgICAgICAyMTgsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTA0LFxuICAgICAgICAxNzksXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjE2LFxuICAgICAgICAyMzAsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTk2LFxuICAgICAgICAxMjAsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTY4LFxuICAgICAgICAyNDUsXG4gICAgICAgIDUxLFxuICAgICAgICA0NCxcbiAgICAgICAgMjI1LFxuICAgICAgICAxMTYsXG4gICAgICAgIDI0LFxuICAgICAgICA5OSxcbiAgICAgICAgNDQsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTIzLFxuICAgICAgICAxMDIsXG4gICAgICAgIDg4LFxuICAgICAgICAxODEsXG4gICAgICAgIDU3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIxNixcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMTAxLFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAyNSxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDExMyxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgMTk0LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAxMTZcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDExMSxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxMzIsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTAxLFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgM1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxNjcsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTYyLFxuICAgICAgICA5LFxuICAgICAgICAxMjMsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMzIsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMjU1LFxuICAgICAgICA0MixcbiAgICAgICAgMjI2LFxuICAgICAgICA1MyxcbiAgICAgICAgMzgsXG4gICAgICAgIDg2LFxuICAgICAgICAyMzQsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTgwLFxuICAgICAgICA0MixcbiAgICAgICAgMjMyLFxuICAgICAgICAyNyxcbiAgICAgICAgMjE0LFxuICAgICAgICAxNzQsXG4gICAgICAgIDIyMyxcbiAgICAgICAgNDIsXG4gICAgICAgIDcyLFxuICAgICAgICA5LFxuICAgICAgICAxMzUsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjMxLFxuICAgICAgICAxNDIsXG4gICAgICAgIDQyLFxuICAgICAgICAyMzIsXG4gICAgICAgIDc4LFxuICAgICAgICAyNSxcbiAgICAgICAgMTYzLFxuICAgICAgICA3NCxcbiAgICAgICAgMTczLFxuICAgICAgICAyMDYsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjA5LFxuICAgICAgICAxMjEsXG4gICAgICAgIDkwLFxuICAgICAgICAyMzEsXG4gICAgICAgIDEzLFxuICAgICAgICAxMCxcbiAgICAgICAgMzYsXG4gICAgICAgIDU5LFxuICAgICAgICA4MCxcbiAgICAgICAgNTEsXG4gICAgICAgIDEyNSxcbiAgICAgICAgNjgsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTIzLFxuICAgICAgICAxOTksXG4gICAgICAgIDI1MCxcbiAgICAgICAgMjU1LFxuICAgICAgICAxMDQsXG4gICAgICAgIDQzLFxuICAgICAgICAxMCxcbiAgICAgICAgMjEzLFxuICAgICAgICAyMjIsXG4gICAgICAgIDBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDI1MSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCI2cEVLa1ZjNlJ5OWZiNkFQTVpxb0t5R3FyZE5YaWlSbk9qaTJWR1hHc1YwPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDkwNzg1MzI5NDdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkExRTM2RjU4MzVCREIyNTc0MzRDM0JDN0I3M0IxN0I4XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNTE5MzQwN1xuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDkwNzg1MzI5NDdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkIwOUQ1RkQzQTRGRkM2QjMwMDBGMTNEN0QwNTM4RUM5XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNTE5MzQxMFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IHRydWVcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIjRFWUc4cnZ1U1F5QVRxMmFFNnY3ZXdcIixcbiAgXCJwaG9uZUlkXCI6IFwiYWQ0ZTYzMDctZGFlMi00NzljLTk1NDctZWQ5ZWIzZDYyYWQ1XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEyOSxcbiAgICAgIDE1NixcbiAgICAgIDIxMixcbiAgICAgIDE0NixcbiAgICAgIDIxMSxcbiAgICAgIDIwMixcbiAgICAgIDE1MixcbiAgICAgIDg2LFxuICAgICAgMTUsXG4gICAgICAxNzAsXG4gICAgICAyMzUsXG4gICAgICAxNDUsXG4gICAgICAxODksXG4gICAgICA1NCxcbiAgICAgIDgxLFxuICAgICAgNjgsXG4gICAgICAyMTUsXG4gICAgICAxNjUsXG4gICAgICAxNDMsXG4gICAgICAyMzZcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTk5LFxuICAgICAgODEsXG4gICAgICAyMTgsXG4gICAgICA0LFxuICAgICAgMjksXG4gICAgICA2MCxcbiAgICAgIDE2MSxcbiAgICAgIDI0MyxcbiAgICAgIDc3LFxuICAgICAgOTUsXG4gICAgICAxMTQsXG4gICAgICA4OCxcbiAgICAgIDU5LFxuICAgICAgNjUsXG4gICAgICAzOSxcbiAgICAgIDc0LFxuICAgICAgMTIyLFxuICAgICAgMTg4LFxuICAgICAgODgsXG4gICAgICAyMjJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiUzlHR0xYRFZcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDkwNzg1MzI5NDc6M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIkJ1c2luZXNzIENvYWNoXCIsXG4gICAgXCJsaWRcIjogXCIzNTQxMjQ3NTE3OTE2MDozQGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0tyQXdQa0JFTGE1MGJZR0dBTWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiaVpXMVNyWE90dGxXVFFjL0RuYmd6RU9EUVhQeHhubU5JcGl5Rm1qTzJrRT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJwb01ieXhnK2Z2aWFEWDFReG5ENXpHdmlrR3Y4SldIckxsbVBEZnp3ejJLc2V1ZUQwUjFOWW1hMmk5N1ZGSEgyUjdsRTBNWkkwMy85NTRicFRwdkNEZz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJwbTNWSGRka0cvM3JNdzFYbDl2c3pSQ0t3YWV3YmlJcnAvcFhCTVFhNFc3TnRXWFNtNFVMU095aHp0aERpRnQ4VzRqc0ZnbzFSN0MweE5LdjRtVzFBZz09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ5MDc4NTMyOTQ3OjNAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgNyxcbiAgICAgICAgICA2MyxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDI0MSxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDY1XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjUxOTM0MDIsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFIclFcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUhyUS5qc29uIjogIntcImtleURhdGFcIjpcImt0YitaZWhNeEgzdU1KUHIzdmVMVXBnQnNBTE01dUVZMjBkRS9Rci9BdDQ9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6NTIzMjQ3NjU4LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjM5MzA4MzQ4NzBcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
